### ISSUE TITLE
create a tutorial on how to make a backup manually

### ISSUE THREAD

**Issue by NeptuneNeptix** [Partur1/fh-faq#3]
i forgot issues exist

ok so make a tutorial or smth on the website and here on how to create/get a backup manually because some people who dont have money and also dont have knowledges about php and sql or smth idfk (example: me!)

**Comment by johanbergh** [comment]
In-Fact, you don't need any programming language knowledge to do so. Will do a PC Version but not sure if it is possible on mobile.

**Comment by notqoid** [comment]
it's possible on mobile. to make a backup manually you just have to download all the files inside your FTP, and then go to your database and click on your database and click the export tab. you'll download database.sql which is the gdps database. to place the backups just upload the files into another ftp server and import database.sql you downloaded from your previous database. i don't guarantee that this will work since i tried doing this once after being banned from gdpsfh and it doesn't work
